### ISSUE TITLE
Release new version of Golem-Core on PyPI

### ISSUE THREAD

**Issue by golmek** [golemfactory/golem-core-python#101]
**Context:**

We are preparing to release updated Jupyter on Golem project on PyPi (https://test.pypi.org/project/golem-jupyter-kernel/0.1.1/) and to wider community. Jupyter on Golem uses Golem Core API as dependency. Currently, to be able to successfully release updated Jupyter on Golem on PyPi we need to use newer version of Golem-Core release too. Unfortunately at this point we cannot any more just point to exact commit on Github.

**We need to have newer version of Golem Core on PyPi. Lack of it blocks further progress with Jupyter on Golem.**

**Acceptance Criteria:**

- Golem Core is updated on PyPi (https://pypi.org/project/golem-core/) with **at least** commit `4e73b3be2ed46f7eb067db1c1f73b61a7e87e6a7`

**Prerequisites:**
- https://github.com/golemfactory/golem-core-python/issues/18

**Additional Information:**

-  It would the most optimal to do that in tandem with this task: https://github.com/golemfactory/golem-core-python/issues/18

**Comment by approxit** [comment]
Uploaded as https://pypi.org/project/golem-api-python/ in version `0.1.1`
