### ISSUE TITLE
Prepare integration tests that cover at least the elements of `golem-core` containing bits from `yapapi`

### ISSUE THREAD

**Issue by approxit** [golemfactory/golem-core-python#55]
As #54 identified `yapapi` bits, before further work in #57 we want to cover that very bits of code with integration tests, which will aid us significantly in later steps.

### Todo:
- [ ] Prepare goth tests for code state of `golem-core` that still uses `yapapi` stuff.
  - Use only latest stable version of `yagna`

**Comment by lucekdudek** [comment]
After seeing results of #54 we decided that additional integration tests are not needed as working examples provide sufficient coverage of planned changes.
