### ISSUE TITLE
Setup nighty integration tests for `golem-core`

### ISSUE THREAD

**Issue by approxit** [golemfactory/golem-core-python#56]
As #55 prepared integration tests for `golem-core`, we want to setup nighty runs that would automatically cover regressions with never versions of yagna, or other golem-stack related stuff.

### Todo:
- [ ] Prepare automatic integration tests run at time according to other nighty tests each night.
  - Use only latest stable version of yagna

**Comment by lucekdudek** [comment]
Our tests are so slim right now I am not sure we need them to run during a night
